version: '3.3'
services:
  mysql:
    image: mariadb:10.5.8
    command: --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_DATABASE: 'productsdb'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./schema.sql:/data/application/init.sql
  web:
    build: .      
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: "jdbc:mysql://mysql:3306/productsdb?useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10"
      DB_USER: 'root'
      DB_PASSWORD: 'password'    
    links:
      - mysql
volumes:
  my-db: