CREATE DATABASE IF NOT EXISTS productsdb;

FLUSH PRIVILEGES;

USE productsdb;

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    quantity INT    
)  ENGINE=INNODB;